# Add this to your configuration.yaml in home assistant
# Change weather.home to what ever your weather. entity is, I have tested this with the default weather entity.
sensor:
  - platform: template
    sensors:
      today_min:
        value_template: "{{ state_attr('weather.home','forecast')[0].templow | default('0') }}"
        friendly_name: Today's maximal temperature
      today_max:
        value_template: "{{ state_attr('weather.home','forecast')[0].temperature | default('0') }}"
        friendly_name: Today's minimal temperature
      current_temperature: 
        value_template: "{{ state_attr('weather.home', 'temperature') | default('69') }}"
        friendly_name: Current Temperature
      today_rain:
        value_template: "{{ state_attr('weather.home','forecast')[0].precipitation | default('0') }}"
        friendly_name: Today's rain forecast
